import { env } from "../config/env.js";
import { runResponseWithTools } from "../services/responsesToolRunner.js";
import { toolRegistry } from "../tools/index.js";
import type { ToolDefinition } from "../tools/types.js";
import type { ToolTrace } from "../types/index.js";
import { runWithAgentsSdk } from "./agentsSdkBridge.js";
import type { AgentName, AgentRunInput, AgentRunOutput } from "./types.js";

function pickTools(toolNames: string[]): ToolDefinition[] {
  return toolNames.map((name) => toolRegistry[name]).filter(Boolean);
}

export async function runAgentWithTools(params: {
  agentName: AgentName;
  systemPrompt: string;
  input: AgentRunInput;
  enabledTools: string[];
}): Promise<AgentRunOutput> {
  const steps = [
    {
      step: "agent_initialized",
      detail: `${params.agentName} selected by orchestrator`,
      timestamp: new Date().toISOString()
    }
  ];

  const selectedTools = pickTools(params.enabledTools);
  const fullPrompt = `${params.systemPrompt}\n\nRetrieved context:\n${params.input.retrievedContext ?? "(none)"}`;

  // Optional: try Agents SDK first for educational parity with modern agent APIs.
  // Tool loop still runs through Responses API so learners can inspect every tool call step.
  if (env.USE_AGENTS_SDK) {
    const sdkResult = await runWithAgentsSdk({
      agentName: params.agentName,
      instructions: fullPrompt,
      userMessage: params.input.userMessage
    });

    if (sdkResult) {
      return {
        agentName: params.agentName,
        answer: sdkResult.text,
        steps: [
          ...steps,
          {
            step: "agents_sdk_completed",
            detail: "Agent output generated by OpenAI Agents SDK",
            timestamp: new Date().toISOString()
          }
        ],
        toolTraces: []
      };
    }
  }

  const result = await runResponseWithTools({
    model: env.OPENAI_MODEL,
    systemPrompt: fullPrompt,
    userMessage: params.input.userMessage,
    tools: selectedTools.map((tool) => ({
      name: tool.name,
      description: tool.description,
      parameters: tool.parameters
    })),
    handlers: Object.fromEntries(
      selectedTools.map((tool) => [
        tool.name,
        (args: Record<string, unknown>) =>
          tool.handler(args, {
            userId: params.input.userId,
            conversationId: params.input.conversationId
          })
      ])
    )
  });

  steps.push(
    {
      step: "tool_phase_completed",
      detail: `${result.traces.length} tool calls executed`,
      timestamp: new Date().toISOString()
    },
    {
      step: "final_answer_generated",
      detail: "Agent returned final answer",
      timestamp: new Date().toISOString()
    }
  );

  return {
    agentName: params.agentName,
    answer: result.text,
    steps,
    toolTraces: result.traces as ToolTrace[]
  };
}
